import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  ContainerLogin: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 15,
  },
  InputLogin: {
    width: 300,
    marginBottom: 8,
    backgroundColor: "white",
    flexDirection: "row",
    borderRadius: 8,
    borderWidth: 1,
    height: 50,
    alignItems: "center",
  },
  TextLogin: {
    fontSize: 28,
    fontWeight: "bold",
    color: "rgb(59, 110, 62)",
    paddingBottom: 10,
  },
  Error: {
    color: "red",
    fontSize: 14,
  },
  InputEdit: {
    backgroundColor: "white",
    width: 300,
    color: "black",
    marginBottom: 5,
  },
  TextEdit: {
    fontSize: 24,
    fontWeight: "bold",
    paddingBottom: 6,
  },
  InputCreate: {
    width: 300,
    borderWidth: 0.5,
    borderRadius: 6,
    color: "black",
    marginBottom: 5,
    marginTop: 5,
  },
  TextCreate: {
    fontWeight: "bold",
    paddingBottom: 6,
    fontSize: 30,
  },
  ErrorCreate: {
    color: "red",
    marginTop: -5,
    marginBottom: 25,
    textAlign: "left",
  },
  ModalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  ModalCardContainer: {
    width: 280,
    minHeight: 400,
    backgroundColor: "white",
    borderRadius: 12,
    padding: 10,
  },
  ModalCard: {
    flexDirection: "row",
    padding: 10,
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    width: "100%",
    alignItems: "center",
  },
  IndexHeader: {
    flexDirection: "row",
    boxShadow: "0 5px 3px -4px gray",
    paddingBottom: 20,
    width: 400,
    justifyContent: "space-between",
    paddingLeft: 40,
    paddingRight: 40,
  },
});
